- name: set hostname facts
  set_fact:
    full_hostname="{{ inventory_hostname}}"

- name: /etc/hosts entry 127.0.0.1 {{full_hostname}}
#  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1    {{full_hostname}} localhost localhost.localdomain localhost4 localhost4.localdomain4' owner=root group=root mode=0644
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1    localhost localhost.localdomain localhost4 localhost4.localdomain4' owner=root group=root mode=0644

- name: /etc/hosts entry ::1 {{full_hostname}}
#  lineinfile: dest=/etc/hosts regexp='^\:\:1' line='::1    {{full_hostname}} localhost localhost.localdomain localhost6 localhost6.localdomain6' owner=root group=root mode=0644
  lineinfile: dest=/etc/hosts regexp='^\:\:1' line='::1    localhost localhost.localdomain localhost6 localhost6.localdomain6' owner=root group=root mode=0644

- name: Create hostname entry to {{full_hostname}}
  lineinfile: dest=/etc/hostname state=present create=yes regexp='.*' line='{{full_hostname}}'

- name: Set networking yes
  lineinfile: dest=/etc/sysconfig/network create=yes state=present regexp='NETWORKING=.*' line='NETWORKING=yes'

- name: Set hostname to {{full_hostname}}
  lineinfile: dest=/etc/sysconfig/network create=yes state=present regexp='HOSTNAME=.*' line='HOSTNAME={{full_hostname}}'
